### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by jakemdaly** [arapat/aws-jupyter#2]
I've successfully set up the config file (verified by `aws-jupyter access` command), but when running the `aws-jupyter create` or `aws-jupyter check` commands, I get a JSONDecodeError from the query_status function inside the check_cluster file.
```
def query_status(args):
    query_command = """
    AWS_ACCESS_KEY_ID="{}" AWS_SECRET_ACCESS_KEY="{}" \
    aws ec2 describe-instances --region {} \
        --filter "Name=tag:cluster-name,Values={}" "Name=instance-state-name,Values=pending,running" \
        --query 'Reservations[*].Instances[*].[State.Name,PublicIpAddress]'
    """.format(
        args["aws_access_key_id"], args["aws_secret_access_key"], args["region"], args["name"])
    result = subprocess.run(query_command, shell=True, check=True, stdout=subprocess.PIPE)
    output = result.stdout
    all_status = json.loads(output)
    return all_status
```
I've tried checking the value of the `output` variable, and it is an empty binary string:

Do you have any insight as to what could be wrong?

Full Traceback
```
Traceback (most recent call last):
File "/home/jakemdaly/.local/bin/aws-jupyter", line 89, in <module>
AwsJupyter()
File "/home/jakemdaly/.local/bin/aws-jupyter", line 38, in init
getattr(self, task)()
File "/home/jakemdaly/.local/bin/aws-jupyter", line 48, in check
(config, status) = main_check_cluster()
File "/home/jakemdaly/.local/lib/python3.7/site-packages/aws_jupyter/check_cluster.py", line 61, in main_check_cluster
status = check_cluster(config)
File "/home/jakemdaly/.local/lib/python3.7/site-packages/aws_jupyter/check_cluster.py", line 12, in check_cluster
all_status = query_status(args)
File "/home/jakemdaly/.local/lib/python3.7/site-packages/aws_jupyter/common.py", line 88, in query_status
all_status = json.loads(output)
File "/usr/lib/python3.7/json/init.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by arapat** [comment]
Hi Jake,

I am looking into it. Meanwhile, the screenshot you provided contains your AWS credentials, so I had to go ahead and delete it. To be safe, please consider generate a new set of credentials (aws access key id and secret) and delete the old ones.

**Comment by jakemdaly** [comment]
Hi, I ended up figuring out that is was due to the fact my AWS CLI output was set to text.
The return value `output` in the code above was an empty text string "", which isn't valid JSON.
Once I changed AWS output to JSON format, it worked fine
